---
title: "AFS505_2022Fall_Exam1"
author: "Chris Benedict"
date: "9/24/2022"
output: html_document
---
## My Level-3 Header Tabset {.tabset}

### Question 1a {.tabset}
```{r Question 1a}
cat("**Question 1a:** What are the basic R data structures?\n")
cat("**Answer:** There are six basic data structures in R. These include: atomic vector, list, array/matrix, data frame, and factors (Source: class notes).\n") 
```

### Question 1b {.tabset}
```{r Question 1b}

cat("**Question 1b:** What are the differences between them?\n")
cat("**Answer:** Atomic vectors and factors are one-dimensional and homogenous. A list is one-dimensional but heterogeneous. A matrix is two-dimensional and homogeneous. Data frames are two-dimensional but heterogeneous. An array is non-dimensional and homogeneous. Vectors are the most basic data structure and a matrix is an atomic vector with dimensions (think rows and columns). Lists are not limited to a single type and may consist of several data types. A data frame is a structured list where all elements have the same length. Factors have set levels and are like character vectors (Source: class notes).\n")
```

### Question 1c {.tabset}
```{r Question 1c}

cat("**Question 1c:** In what context would you use one versus the other?\n")
cat("**Answer:** Vectors are used when working with one data type. In contrast, lists would be used when you are working with heterogeneous data types. Like vectors, matrices are homogenous but are two-dimensional in a grid-like fashion. Factors are commonly used in data analysis for statistical modeling. Data frames are commonly used in the analysis of scientific data as they are arraigned in a two-dimensional grid with columns and rows.  This structure is desirable when working with data that is described by two factors (row and column) and the data itself can be of various types (numeric, factor, or character). 
(Source: https://swcarpentry.github.io/r-novice-inflammation/13-supp-data-structures/, https://www.geeksforgeeks.org/data-structures-in-r-programming/, https://intellipaat.com/blog/tutorial/r-programming/data-structures-r-programming/).\n")
```

### Question 2a and 2b {.tabset}
```{r Question 2a and b}

#set working directory to desktop folder
setwd("/Users/chrisbenedict/Desktop/AFS505DataFolder/Exam1")
library("tidyverse")
library("stringr")
library(tidyr)

#search directory for all files and create values out of all absolute file paths
filelist <- list.files ("/Users/chrisbenedict/Desktop/AFS505DataFolder/Exam1/CropModelResults", all.files = FALSE, recursive = TRUE)
filelist
combined_data <- NULL 
for (file.name in 1: length(filelist)) {
  #current_file_name <- filelist[file.name]
  current_file_name <- paste0("/Users/chrisbenedict/Desktop/AFS505DataFolder/Exam1/CropModelResults/",filelist[file.name])
  current_data <- read.csv(current_file_name)
  information_string <- str_split(filelist[file.name], "/")
  current_data$countyname <- information_string[[1]][1]
  current_data$cropname <- information_string[[1]][2]
  current_data$latlong <- information_string[[1]][3]
  combined_data <- rbind(combined_data, current_data)
}
current_data
```

### Question 2c {.tabset}
```{r Question 2c}

combined_data_colnames <- colnames(combined_data)
cat("colnames(combined_data)")
combined_data_colnames

combined_data_colnames <- gsub('precip', 'precipitation', combined_data_colnames)
combined_data_colnames <- gsub('irrig', 'irrigation_demand', combined_data_colnames)
cat("modified colnames(combined_data)")
combined_data_colnames

colnames(combined_data) <- combined_data_colnames
head(combined_data)

write.csv(combined_data,"/Users/chrisbenedict/Library/CloudStorage/OneDrive-WashingtonStateUniversity(email.wsu.edu)/Documents/Work Docs/2022/Coursework/AFS 505/Exams/AFS505_Exam1_Q2c_Benedict.csv", row.names = FALSE)
```

### Question 2d {.tabset}
```{r Question 2d}

cat("summarize annual irrigation deman by crop name and county name\n")
with(combined_data, tapply(irrigation_demand, INDEX=list(cropname, countyname),FUN=sum))
```

### Question 2e {.tabset}
```{r Question 2e}

#average yield of Winter Wheat in Walla Walla at 46.03125N118.40625W for the year ranges (1981-1990), (1991-2000), and (2001-2019)
#1981-1990
walla_crop_loc_per1 <- combined_data[278:287,]
walla_crop_loc_per1

walla_crop_loc_per2 <- combined_data[288:297,]
walla_crop_loc_per2

walla_crop_loc_per3 <- combined_data[298:316,]
walla_crop_loc_per3

cat("Average winter wheat yield Walla Walla site ending in 625, 1981-1990\n")
mean(walla_crop_loc_per1$yield)
cat("Average winter wheat yield Walla Walla site ending in 625, 1991-2000\n")
mean(walla_crop_loc_per2$yield)
cat("Average winter wheat yield Walla Walla site ending in 625, 2001-2019\n")
mean(walla_crop_loc_per3$yield)
```

### Question 2f {.tabset}
```{r Question 2f}

combined_data$year <- str_sub(combined_data$YYYY.MM.DD.DOY., 1, 4)
combined_data

combined_data_2001_2019 <- subset(combined_data, combined_data$year>2000 & combined_data$year<2020) 

cat("Location with the highest yield (average) for the time period (2001-2019) for
grain corn\n\n")
combined_data_2f <- with(combined_data_2001_2019, tapply(yield, INDEX=list(cropname, latlong),FUN=mean))
combined_data_2f


cat("Looks like the Yakima 46.21875N119.34375W site had the highest grain corn yield average between 2001-2019")
```
### Question 3 {.tabset}
```{r Question 3}

cat("**Question 3**:Was the data provided to you well described ? If not, what information was missing? Comment on what kind of metadata (description about the data) should be included as as best practice while sharing datasets?\n")

cat("**Answer:** The data could use more description to make it useful for analysis. For example, no units on yield data were provided so we don't even know if there are in the same units across sites. Variety or hybrid details were also not provided so as it currently stands we cannot meaninfully analyze this data across sites. Especially since we are talking a time period of roughly 40 years. How were each of the crops seeded? What were the seeding rates? What unit is the irrigation data? Also the used biomass column is zero across all data points.\n") 
```

### Github link
```{r}
cat("Here is the Github link:https://github.com/christopherbenedict/AFS505_Fall2022/tree/main")

```

